# Generated by Django 4.1.1 on 2022-09-27 11:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0077_alter_revision_user'),
        ('home', '0003_homepage_image_banner_homepage_sub_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('description', wagtail.blocks.RichTextBlock(default='First album', features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'hr'], label='Description')), ('photo_album', wagtail.images.blocks.ImageChooserBlock(required=False))], use_json_field=None, verbose_name='Contenu')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='UserFeedPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('user_photo', wagtail.images.blocks.ImageChooserBlock(required=False))], use_json_field=None, verbose_name='Contenu')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='UserProfilePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('bio', wagtail.blocks.RichTextBlock(default='I am a Software developer', features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'hr'], label='Biography')), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False))], use_json_field=None, verbose_name='Contenu')),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='UserDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('tag', wagtail.blocks.RichTextBlock(default='I am a Software developer', features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'hr'], label='Tag')), ('comment', wagtail.blocks.RichTextBlock(default='I am fun', features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'hr'], label='Comment')), ('like', wagtail.blocks.RichTextBlock(default='I like your comment', features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'hr'], label='Like'))], use_json_field=None, verbose_name='Contenu')),
                ('photo_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
