# Generated by Django 4.1.1 on 2022-09-27 12:10

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_userprofilepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepage',
            name='body',
            field=wagtail.fields.StreamField([('photo', wagtail.images.blocks.ImageChooserBlock(required=False))], use_json_field=None, verbose_name='Contenu'),
        ),
    ]
