# Generated by Django 4.1.1 on 2022-09-27 17:59

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_photopage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photopage',
            options={'verbose_name': 'page de photo'},
        ),
        migrations.AlterField(
            model_name='photopage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'hr'], label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('two_columns', wagtail.blocks.StructBlock([('position', wagtail.blocks.ChoiceBlock(choices=[('left', '70%-30%'), ('middle', '50%-50%'), ('right', '30%-70%')], label='Disposition des colonnes')), ('left_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-left', label='Colonne de gauche')), ('right_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-right', label='Colonne de droite'))])), ('three_columns', wagtail.blocks.StructBlock([('left_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-left', label='Colonne de gauche')), ('middle_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Colonne centrale')), ('right_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-right', label='Colonne de droite'))])), ('photos', wagtail.blocks.StructBlock([('left_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-left', label='Colonne de gauche')), ('middle_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Colonne centrale')), ('right_column', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-right', label='Colonne de droite'))]))], null=True, use_json_field=None, verbose_name='Contenu'),
        ),
    ]
