# Generated by Django 4.1.1 on 2022-09-27 18:28

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_photopage_options_alter_photopage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photopage',
            options={},
        ),
        migrations.AlterField(
            model_name='photopage',
            name='body',
            field=wagtail.fields.StreamField([('photo_page', wagtail.images.blocks.ImageChooserBlock(required=False))], use_json_field=None, verbose_name='Contenu'),
        ),
    ]
